sudo: required
services:
    - docker

before_install:
    - docker build -t rudy207/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true rudy207/react-test npm test

after_success:
    - docker build -t rudy207/multi-client ./client
    - docker build -t rudy207/multi-nginx ./nginx
    - docker build -t rudy207/multi-server ./server
    - docker build -t rudy207/multi-worker ./worker
    #Log in to the docker CLI changes
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
    #Push to docker hub
    - docker push rudy207/multi-client
    - docker push rudy207/multi-nginx
    - docker push rudy207/multi-server
    - docker push rudy207/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-2-133251300820"
    bucket_path: "multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


